# Generated by Django 6.0.4 on 2026-04-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cable_type', models.CharField(choices=[('288F', '288F'), ('96F', '96F'), ('48F', '48F'), ('24F', '24F'), ('12F', '12F'), ('4F', '4F')], max_length=10)),
                ('mode', models.CharField(choices=[('OH', 'Overhead'), ('UG', 'Underground')], max_length=2)),
                ('category', models.CharField(choices=[('IN', 'IN Cable'), ('OUT', 'OUT Cable'), ('TIE', 'Tie Cable')], max_length=3)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('CPAN_B', 'CPAN B Node'), ('MAAN_C', 'MAAN C Node'), ('MAAN_A3_A4', 'MAAN A3 / A4 Node'), ('MADM', 'MADM'), ('LCO_OLT', 'LCO OLT'), ('LMG', 'LMG'), ('NGN_SWITCH', 'NGN Switch'), ('MNG_PAN', 'MNG PAN')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('uplink_connectivity', models.CharField(max_length=255)),
                ('total_ports', models.PositiveIntegerField(default=0)),
                ('used_ports', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JunctionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jb_id', models.CharField(max_length=100, unique=True)),
                ('cable_mode', models.CharField(choices=[('OH', 'Overhead'), ('UG', 'Underground')], max_length=2)),
                ('jb_type', models.CharField(choices=[('BAMBOO_BIG', 'Bamboo Big'), ('BAMBOO_SMALL', 'Bamboo Small'), ('SQUARE_BIG', 'Square Big'), ('SQUARE_SMALL', 'Square Small')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NWO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CENTRAL', 'Central NWO'), ('PALARIVATTOM', 'Palarivattom NWO'), ('KOCHI', 'Kochi NWO'), ('TRIPUNITHARA', 'Tripunithara NWO')], max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileBTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_id', models.CharField(max_length=100, unique=True)),
                ('maan_port', models.CharField(max_length=50)),
                ('cable_name', models.CharField(max_length=100)),
                ('is_ring', models.BooleanField(default=False)),
                ('ring_info', models.TextField(blank=True, null=True)),
                ('erps_image', models.ImageField(blank=True, null=True, upload_to='bts_images/')),
                ('receive_power_db', models.DecimalField(decimal_places=2, max_digits=5)),
                ('has_cef_circuit', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('maan_node', models.ForeignKey(limit_choices_to={'equipment_type__startswith': 'MAAN'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('nwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='inventory.nwo')),
            ],
            options={
                'unique_together': {('nwo', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(choices=[(12, '12'), (24, '24'), (48, '48'), (96, '96')])),
                ('remarks', models.TextField()),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cable')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.telephoneexchange')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.telephoneexchange'),
        ),
        migrations.CreateModel(
            name='EBCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_type', models.CharField(choices=[('LL', 'LL'), ('KSWAN', 'KSWAN'), ('ILL', 'ILL'), ('PRI', 'PRI'), ('P2P', 'P2P'), ('POI', 'POI'), ('FTTH', 'FTTH'), ('CAMERA', 'Camera')], max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('bandwidth', models.CharField(max_length=50)),
                ('customer_end_node', models.CharField(max_length=100)),
                ('fiber_mode', models.CharField(choices=[('SINGLE', 'Single'), ('DUAL', 'Dual')], max_length=10)),
                ('remarks', models.TextField()),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cable')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.telephoneexchange')),
            ],
        ),
        migrations.AddField(
            model_name='cable',
            name='connected_te',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_cables', to='inventory.telephoneexchange'),
        ),
        migrations.AddField(
            model_name='cable',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='inventory.telephoneexchange'),
        ),
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_number', models.PositiveIntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibers', to='inventory.cable')),
            ],
            options={
                'ordering': ['fiber_number'],
                'unique_together': {('cable', 'fiber_number')},
            },
        ),
    ]
