# Generated by Django 6.0.4 on 2026-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ebcircuit_latitude_ebcircuit_longitude_liu_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_ports',
            field=models.PositiveIntegerField(),
        ),
    ]
