# Generated by Django 6.0.4 on 2026-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_latitude_equipment_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiber',
            name='circuit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fiber',
            name='system_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
