# Generated by Django 6.0.4 on 2026-04-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fiber_circuit_name_fiber_system_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='junctionbox',
            name='te',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junction_boxes', to='inventory.telephoneexchange'),
        ),
    ]
