# Generated by Django 6.0.4 on 2026-04-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_junctionbox_te'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fiber_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spliced_in', to='inventory.fiber')),
                ('fiber_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spliced_out', to='inventory.fiber')),
                ('jb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splices', to='inventory.junctionbox')),
            ],
            options={
                'verbose_name_plural': 'Splicing Records',
                'unique_together': {('fiber_in', 'fiber_out')},
            },
        ),
    ]
