# Generated by Django 6.0.4 on 2026-04-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_splicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='liu',
            name='name',
            field=models.CharField(default='Main LIU', max_length=100),
        ),
        migrations.CreateModel(
            name='LIUPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField()),
                ('connected_to', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fiber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fiber')),
                ('liu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.liu')),
            ],
            options={
                'ordering': ['port_number'],
                'unique_together': {('liu', 'port_number')},
            },
        ),
    ]
