# Generated by Django 5.2.13 on 2026-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_liu_name_liuport'),
    ]

    operations = [
        migrations.AddField(
            model_name='junctionbox',
            name='input_cables',
            field=models.ManyToManyField(blank=True, related_name='jb_inputs', to='inventory.cable'),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='jb_image',
            field=models.ImageField(blank=True, null=True, upload_to='jb_images/'),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='output_cables',
            field=models.ManyToManyField(blank=True, related_name='jb_outputs', to='inventory.cable'),
        ),
        migrations.AlterField(
            model_name='junctionbox',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='junctionbox',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
