# Generated by Django 5.2.13 on 2026-04-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_junctionbox_input_cables_junctionbox_jb_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('order', models.PositiveIntegerField()),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='inventory.cable')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('cable', 'order')},
            },
        ),
    ]
