# Generated by Django 5.2.13 on 2026-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_cableroutepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcircuit',
            name='circuit_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nwo',
            name='name',
            field=models.CharField(choices=[('CENTRAL', 'NWO Central DIV'), ('PALARIVATTOM', 'NWO Palarivattom DIV'), ('KOCHI', 'NWO Kochi DIV'), ('TRIPUNITHARA', 'NWO Tripunithara DIV')], max_length=50, unique=True),
        ),
    ]
