# Generated by Django 5.2.13 on 2026-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ebcircuit_circuit_type_alter_nwo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
