# Generated by Django 5.2.13 on 2026-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_equipment_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcircuit',
            name='mc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='node_configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebcircuit',
            name='customer_end_node',
            field=models.CharField(choices=[('MEDIA_CONVERTER', 'Media Converter'), ('CPE', 'CPE'), ('A_NODE', 'A-Node'), ('CPAN_B', 'CPAN B-Node'), ('MRO_TEK', 'MRO TEK Modem'), ('FTTH_MODEM', 'FTTH Modem'), ('MADM', 'MADM'), ('MAAN_A3_A4', 'MAAN A3 / A4 Node')], max_length=50),
        ),
    ]
