# Generated by Django 5.2.13 on 2026-04-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_ebcircuit_mc_type_ebcircuit_node_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcircuit',
            name='customer_premise_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='otdr_distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
