# Generated by Django 5.2.13 on 2026-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_ebcircuit_customer_premise_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junctionbox',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='fiber_entering',
            field=models.CharField(blank=True, help_text='Fiber types entering JB (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='fiber_out',
            field=models.CharField(blank=True, help_text='Fiber types leaving JB (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='jb_name',
            field=models.CharField(blank=True, help_text='Friendly name for the Junction Box', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='splicing_info',
            field=models.TextField(blank=True, help_text='Splicing information (e.g., 96F → 48F + 48F split)', null=True),
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='junctionbox',
            name='cable_mode',
            field=models.CharField(choices=[('UG', 'Underground'), ('OH', 'Overhead')], max_length=2),
        ),
    ]
