# Generated by Django 5.2.13 on 2026-05-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_junctionbox_options_junctionbox_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splicing',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Splicing Records'},
        ),
        migrations.AddField(
            model_name='splicing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
