# Generated by Django 5.2.13 on 2026-05-02 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_splicing_options_splicing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='otdr_distance',
            field=models.FloatField(blank=True, help_text='Stored in meters', null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='otdr_image',
            field=models.ImageField(blank=True, null=True, upload_to='cable_otdr_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
        ),
    ]
