# Generated by Django 5.2.13 on 2026-05-02 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_cable_otdr_distance_cable_otdr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiber',
            name='otdr_distance',
            field=models.FloatField(blank=True, help_text='Stored in meters', null=True),
        ),
        migrations.AddField(
            model_name='fiber',
            name='otdr_image',
            field=models.ImageField(blank=True, null=True, upload_to='fiber_otdr_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
        ),
    ]
