# Generated by Django 5.2.13 on 2026-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_fiber_otdr_distance_fiber_otdr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='structure_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RIBBON', 'Ribbon')], default='NORMAL', max_length=10, verbose_name='Cable Category'),
        ),
    ]
