# Generated by Django 5.2.13 on 2026-05-04 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_cable_structure_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwo',
            name='name',
            field=models.CharField(choices=[('CENTRAL', 'NWO Central DIV'), ('PALARIVATTOM', 'NWO Palarivattom DIV'), ('KOCHI', 'NWO Kochi DIV'), ('TRIPUNITHURA', 'NWO Tripunithura DIV')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_no', models.CharField(max_length=20, unique=True, verbose_name='PER NO')),
                ('designation', models.CharField(max_length=50)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nwo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
