# Generated by Django 5.2.13 on 2026-05-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_nwo_name_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcircuit',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
