# Generated by Django 5.2.13 on 2026-05-05 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_ebcircuit_landline_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('landline_number', models.CharField(max_length=20, unique=True)),
                ('optical_power', models.DecimalField(decimal_places=2, help_text='Format: -XX.XX dB', max_digits=5)),
                ('olt_name', models.CharField(max_length=255)),
                ('port_number', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nwo')),
                ('te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.telephoneexchange')),
            ],
            options={
                'verbose_name': 'FTTH Record',
                'verbose_name_plural': 'FTTH Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
