# Generated by Django 5.2.13 on 2026-05-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_ftth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebcircuit',
            name='landline_number',
        ),
    ]
