# Generated by Django 5.2.13 on 2026-05-06 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_ebcircuit_landline_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebts',
            name='has_cef_circuit',
        ),
        migrations.RemoveField(
            model_name='mobilebts',
            name='ring_info',
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='bts_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BTS Name'),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='cef_ports_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='has_cef_12t',
            field=models.BooleanField(default=False, verbose_name='Is CEF Having 12T'),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='cable_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='erps_image',
            field=models.ImageField(blank=True, help_text='Upload ERPS Connectivity Diagram (JPG only)', null=True, upload_to='bts_images/'),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='is_ring',
            field=models.BooleanField(default=False, verbose_name='Is BTS in Ring'),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='maan_node',
            field=models.ForeignKey(blank=True, limit_choices_to={'equipment_type__startswith': 'MAAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='maan_port',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='receive_power_db',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='rp_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='RP ID'),
        ),
        migrations.AlterField(
            model_name='nwo',
            name='name',
            field=models.CharField(choices=[('NWO CENTRAL', 'NWO CENTRAL'), ('NWO PALARIVATTOM', 'NWO PALARIVATTOM'), ('NWO KOCHI', 'NWO KOCHI'), ('NWO TRIPUNITHARA', 'NWO TRIPUNITHARA'), ('NWO ANGAMALY', 'NWO ANGAMALY'), ('NWO THODUPUZHA', 'NWO THODUPUZHA'), ('NWO ALUVA', 'NWO ALUVA'), ('NWO MOOVATTUPUZHA', 'NWO MOOVATTUPUZHA'), ('NWO ADIMALY', 'NWO ADIMALY'), ('NWO KATTAPPANA', 'NWO KATTAPPANA')], max_length=50, unique=True),
        ),
    ]
