# Generated by Django 5.2.13 on 2026-05-06 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_mobilebts_has_cef_circuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebts',
            name='bts_name',
            field=models.CharField(default='Unnamed BTS', max_length=255, verbose_name='BTS Name'),
        ),
        migrations.AlterField(
            model_name='mobilebts',
            name='erps_image',
            field=models.ImageField(blank=True, help_text='Upload ERPS Connectivity Diagram (JPG only)', null=True, upload_to='bts_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
        ),
    ]
