# Generated by Django 5.2.13 on 2026-05-08 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_mobilebts_bts_name_alter_mobilebts_erps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcircuit',
            name='is_ring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='ring_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_ring_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='ring_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('CPAN_B', 'CPAN B Node'), ('MAAN_C', 'MAAN C Node'), ('MAAN_A3_A4', 'MAAN A3 / A4 Node'), ('MADM', 'MADM'), ('BSNL_OLT', 'BSNL OLT'), ('LCO_OLT', 'LCO OLT'), ('LMG', 'LMG'), ('NGN_SWITCH', 'NGN Switch'), ('MNG_PAN', 'MNG PAN')], max_length=50),
        ),
    ]
