# Generated by Django 5.2.13 on 2026-05-13 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_liu_manual_cable_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OHMaintenanceRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('OFC Cable Splicing', 'OFC Cable Splicing'), ('Re-shackling / Tightening of Sagged Cable', 'Re-shackling / Tightening of Sagged Cable'), ('Assembling and Erection of Cable Post', 'Assembling and Erection of Cable Post'), ('Erection of Aerial OFC up to 12F', 'Erection of Aerial OFC up to 12F'), ('Dismantling and Recovery of Unused Cables', 'Dismantling and Recovery of Unused Cables'), ('BSNL Name Tagging on OH Cables', 'BSNL Name Tagging on OH Cables')], max_length=100)),
                ('unit_type', models.CharField(choices=[('Per Splice', 'Per Splice'), ('Per Span', 'Per Span'), ('Per Post', 'Per Post'), ('Per Meter', 'Per Meter'), ('Per Tag', 'Per Tag')], max_length=50)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'OH Maintenance Rate Master',
                'verbose_name_plural': 'OH Maintenance Rate Masters',
            },
        ),
        migrations.CreateModel(
            name='OHMaintenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('team_name', models.CharField(max_length=255)),
                ('work_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pole_span_details', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('fault_ticket_no', models.CharField(blank=True, max_length=100, null=True)),
                ('fault_type', models.CharField(blank=True, choices=[('Cable Cut', 'Cable Cut'), ('Sagging Cable', 'Sagging Cable'), ('Pole Damage', 'Pole Damage'), ('Loose Shackling', 'Loose Shackling'), ('Fiber Break', 'Fiber Break'), ('Cable Theft', 'Cable Theft'), ('Wind / Rain Damage', 'Wind / Rain Damage'), ('Vehicle Hit Damage', 'Vehicle Hit Damage'), ('Joint Failure', 'Joint Failure'), ('Others', 'Others')], max_length=50, null=True)),
                ('fault_occurrence_datetime', models.DateTimeField(blank=True, null=True)),
                ('fault_clearance_datetime', models.DateTimeField(blank=True, null=True)),
                ('fault_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('fault_severity', models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Medium', 'Medium'), ('Major', 'Major'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('fault_cause', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oh_entries_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oh_entries_created', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nwo')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oh_entries_modified', to=settings.AUTH_USER_MODEL)),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.telephoneexchange')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oh_entries_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OH Maintenance Entry',
                'verbose_name_plural': 'OH Maintenance Entries',
                'ordering': ['-maintenance_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OHMaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(max_length=50)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inventory.ohmaintenanceentry')),
            ],
            options={
                'verbose_name': 'OH Maintenance Activity',
                'verbose_name_plural': 'OH Maintenance Activities',
            },
        ),
    ]
