# Generated by Django 5.2.13 on 2026-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_ohmaintenanceratemaster_ohmaintenanceentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='transnet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TRANSNET ID'),
        ),
    ]
