# Generated by Django 6.0.4 on 2026-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_cable_transnet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcircuit',
            name='circuit_type',
            field=models.CharField(choices=[('INTERNET LC', 'INTERNET LC'), ('P2P LC', 'P2P LC'), ('P2P LC ACROSS STATE', 'P2P LC ACROSS STATE'), ('MPLS VPN', 'MPLS VPN'), ('ISDN PRI', 'ISDN PRI')], max_length=100),
        ),
    ]
