# Generated by Django 6.0.4 on 2026-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_ebcircuit_circuit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcircuit',
            name='a_address',
            field=models.TextField(blank=True, null=True, verbose_name='A-Address'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='a_media',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='A-Media'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='cable_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cable Data'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='lc_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LC ID'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='node_at_a_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Node at A-End'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='node_at_b_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Node at B-End'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='port_b_side',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Port - B Side'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ebcircuit',
            name='working_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Working Status'),
        ),
    ]
