# Generated by Django 6.0.4 on 2026-06-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_ebcircuit_a_address_ebcircuit_a_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcircuit',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ebcircuit',
            name='circuit_type',
            field=models.CharField(blank=True, choices=[('INTERNET LC', 'INTERNET LC'), ('P2P LC', 'P2P LC'), ('P2P LC ACROSS STATE', 'P2P LC ACROSS STATE'), ('MPLS VPN', 'MPLS VPN'), ('ISDN PRI', 'ISDN PRI')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebcircuit',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ebcircuit',
            name='customer_end_node',
            field=models.CharField(blank=True, choices=[('MEDIA_CONVERTER', 'Media Converter'), ('CPE', 'CPE'), ('A_NODE', 'A-Node'), ('CPAN_B', 'CPAN B-Node'), ('MRO_TEK', 'MRO TEK Modem'), ('FTTH_MODEM', 'FTTH Modem'), ('MADM', 'MADM'), ('MAAN_A3_A4', 'MAAN A3 / A4 Node')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ebcircuit',
            name='fiber_mode',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('DUAL', 'Dual')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ebcircuit',
            name='te',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.telephoneexchange'),
        ),
    ]
