# Generated by Django 6.0.4 on 2026-06-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_ebcircuit_bandwidth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebts',
            name='backhaul_media',
            field=models.CharField(blank=True, choices=[('FIBER', 'Fiber'), ('MICROWAVE', 'Microwave'), ('LEASED_LINE', 'Leased Line')], max_length=100, null=True, verbose_name='Backhaul Media'),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='connected_equipment',
            field=models.CharField(blank=True, help_text='e.g. BSC, RNC, MSC, IP-BST', max_length=255, null=True, verbose_name='Connected Node/Equipment'),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='non_4g_type',
            field=models.CharField(blank=True, choices=[('2G', '2G'), ('3G', '3G'), ('5G', '5G'), ('2G_3G', '2G + 3G'), ('3G_5G', '3G + 5G'), ('2G_3G_5G', '2G + 3G + 5G')], max_length=50, null=True, verbose_name='No 4G Site Type'),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='site_type',
            field=models.CharField(choices=[('4G', '4G Site'), ('NON_4G', 'No 4G Site')], default='4G', max_length=20, verbose_name='Site Type'),
        ),
        migrations.AddField(
            model_name='mobilebts',
            name='te',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bts_sites', to='inventory.telephoneexchange', verbose_name='Telephone Exchange'),
        ),
    ]
