# Generated by Django 4.2.11 on 2026-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_equipment_ba_equipment_make_equipment_model_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebts',
            name='erps_ring_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ERPS Ring Name'),
        ),
    ]
